---
title: "KM vs PI3K"
author: "P Barber"
date: "29 January 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Load data.

```{r}
load(file = "COIN_Final.Rdata")
```

#Survival Curves split by PIK3CA value and TRT in full data set

```{r, echo=F}

data <- patient_data

library(survival)
data$SurvObj.pfs <- with(data, Surv(pfstime, pfsevent))
data$SurvObj.os <- with(data, Surv(ostime, osevent))
col=c("red", "red", "blue", "blue") 
lty=c(1,2,1,2)

km <- survfit(SurvObj.pfs ~ PIK3CA + TRT, data=data)
plot(km, col=col, xlab="PFS days", ylab="Prob. survival", lty = lty)
legend("topright", col=col, legend = names(km$strata), lty = lty)
print(km)

survdiff(SurvObj.pfs ~ PIK3CA, data=data)
survdiff(SurvObj.pfs[PIK3CA=="Wild-type"] ~ TRT[PIK3CA=="Wild-type"], data=data)
survdiff(SurvObj.pfs[PIK3CA=="Mutation"] ~ TRT[PIK3CA=="Mutation"], data=data)

km <- survfit(SurvObj.os ~ PIK3CA + TRT, data=data)
plot(km, col=col, xlab="OS days", ylab="Prob. survival", lty = lty)
legend("topright", col=col, legend = names(km$strata), lty=lty)
print(km)

survdiff(SurvObj.os ~ PIK3CA, data=data)
survdiff(SurvObj.os[PIK3CA=="Wild-type"] ~ TRT[PIK3CA=="Wild-type"], data=data)
survdiff(SurvObj.os[PIK3CA=="Mutation"] ~ TRT[PIK3CA=="Mutation"], data=data)

```

#Survival Curves split by PIK3CA value and TRT in FRET data set

```{r, echo=F}

data <- patient_data[patient_data$FRET.cohort == 1,]

library(survival)
data$SurvObj.pfs <- with(data, Surv(pfstime, pfsevent))
data$SurvObj.os <- with(data, Surv(ostime, osevent))
col=c("red", "red", "blue", "blue") 
lty=c(1,2,1,2)

km <- survfit(SurvObj.pfs ~ PIK3CA + TRT, data=data)
plot(km, col=col, xlab="PFS days", ylab="Prob. survival", lty = lty)
legend("topright", col=col, legend = names(km$strata), lty = lty)
print(km)

survdiff(SurvObj.pfs ~ PIK3CA, data=data)
survdiff(SurvObj.pfs[PIK3CA=="Wild-type"] ~ TRT[PIK3CA=="Wild-type"], data=data)
survdiff(SurvObj.pfs[PIK3CA=="Mutation"] ~ TRT[PIK3CA=="Mutation"], data=data)

km <- survfit(SurvObj.os ~ PIK3CA + TRT, data=data)
plot(km, col=col, xlab="OS days", ylab="Prob. survival", lty = lty)
legend("topright", col=col, legend = names(km$strata), lty=lty)
print(km)

survdiff(SurvObj.os ~ PIK3CA, data=data)
survdiff(SurvObj.os[PIK3CA=="Wild-type"] ~ TRT[PIK3CA=="Wild-type"], data=data)
survdiff(SurvObj.os[PIK3CA=="Mutation"] ~ TRT[PIK3CA=="Mutation"], data=data)

```

#Session Information

```{r}
sessionInfo()
```