---
title: "Original Post-hoc Analysis"
author: "P Barber"
date: "18 March 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Post-hoc analysis suggests there is more benefit for the addition of cetuximab for patients with KRAS wild-type tumors, who are treated with infusional 5-FU (OxMdg) rather than capecitabine (XELOX), had zero or one metastatic site, or liver only metastatic disease (N=96, HR=0.55, 95% CI 0.35-0.87, p=0.011).

Load data.

```{r}
load(file = "COIN_Final.Rdata")
```

Filter patients.

```{r}

data <- patient_data

data <- data[data$KRAS=="Wild-type",]
data <- data[data$CHEMO=="OxMdG",]
data <- data[data$metsites<2 | data$mlivonly=="Yes",]

```

How many left in each treatment arm?

```{r}
table(data$TRT)
```

Plot KM etc.

```{r}
library(survival)
#library("survminer")

data$SurvObj.pfs <- with(data, Surv(pfstime, pfsevent))
data$SurvObj.os <- with(data, Surv(ostime, osevent))
col=c("red", "blue") 
lty=c(1,1)

km <- survfit(SurvObj.pfs ~ TRT, data=data)
plot(km, col=col, xlab="PFS days", ylab="Prob. survival", lty = lty)
legend("topright", col=col, legend = names(km$strata), lty = lty)
print(km)

survdiff(SurvObj.pfs ~ TRT, data=data)
cox <- coxph(SurvObj.pfs ~ TRT, data=data)
summary(cox)

km <- survfit(SurvObj.os ~ TRT, data=data)
plot(km, col=col, xlab="OS days", ylab="Prob. survival", lty = lty)
legend("topright", col=col, legend = names(km$strata), lty=lty)
print(km)

survdiff(SurvObj.os ~ TRT, data=data)
cox <- coxph(SurvObj.os ~ TRT, data=data)
summary(cox)

```

#Session Information

```{r}
sessionInfo()
```


