---
title: "FULL LCA Analysis"
author: "P R Barber"
date: "22 October 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(survminer)

JNCI_pvals <- function(p){
  if(is.na(p)){
    return("")
  }
  else if(p<0.001){
    return("<0.001***")
  } 
  else if(p==0.001){
    return("0.001***")
  } 
  else if (p<0.01){
    return(paste0(format(round(p, 3), nsmall = 3), "**"))
  }
  else if (p<0.05){
    return(paste0(format(round(p, 2), nsmall = 2), "*"))
  }
  else{
    return(format(round(p, 2), nsmall = 2))
  }
}

```


```{r}
load(file = "COIN_Final.Rdata")
```

#Forest plot of covariates

```{r, echo=F, fig.height=8}
source("plotHRTable.R")
library(filesstrings)

OS_LCA <- LCA_OS_HR

# Change any covarite names
OS_LCA$description <- OS_LCA$Covname
OS_LCA$description <- 
  sub("TRT.B", "TRT arm B", OS_LCA$description)
OS_LCA$description <- 
  sub("ADJCH._1m_6mago", "Adj. Chemo >1m <6m ago", OS_LCA$description)
OS_LCA$description <- 
  sub("SUMLES", "Sum of longest diameter", OS_LCA$description)
OS_LCA$description <- 
  sub("metsites", "Number of mets sites", OS_LCA$description)
OS_LCA$description <- 
  sub("WBC", "White blood cell count", OS_LCA$description)
OS_LCA$description <- 
  sub("WHO", "WHO performance status", OS_LCA$description)
OS_LCA$description <- 
  sub("NEUT", "Neutrophil count", OS_LCA$description)
OS_LCA$description <- 
  sub("ALKP", "Alkaline phosphatase", OS_LCA$description)
OS_LCA$description <- 
  sub("SHB0", "Haemaglobin (CTC grade)", OS_LCA$description)
OS_LCA$description <- 
  sub("SPAIN0", "Pain", OS_LCA$description)
#OS_LCA$description <- 
#  sub("FRET", "HER2-HER3 FRET efficiency", OS_LCA$description)
OS_LCA$description <- 
  sub("mlivonly", "Liver-only metastases", OS_LCA$description)
OS_LCA$description <- 
  sub("PIK3CA.Mutation", "PIK3CA mutation", OS_LCA$description)
OS_LCA$description <- 
  sub("RAS.Mutation", "RAS mutation", OS_LCA$description)
OS_LCA$description <- 
  sub("BRAF.Mutation", "BRAF mutation", OS_LCA$description)
OS_LCA$description <- 
  sub("nEREG", "EREG Cq value (negated)", OS_LCA$description)



# insert rows of NA to break the classes up, do lower one first - easier to track row numbers
insert_row <- c(NA,NA,NA,"","","")
OS_LCA = rbind(OS_LCA[1:22,], insert_row, OS_LCA[-(1:22),])
OS_LCA = rbind(OS_LCA[1:11,], insert_row, OS_LCA[-(1:11),])

#Fix for partially performatted pvals
prefix <- ifelse(!is.na(first_non_numeric(OS_LCA$p.value, decimals=T)), first_non_numeric(OS_LCA$p.value, decimals=T), "")
pval <- paste0(prefix, sapply(as.numeric(first_number(OS_LCA$p.value, decimals=T)), JNCI_pvals))

mydf <- data.frame(
    Covariate = OS_LCA$description,
    Class = OS_LCA$Class,
    HazardRatio = as.numeric(OS_LCA$HR),
    HazardLower = first_number(OS_LCA$X95.CI, decimals=T),
    HazardUpper = nth_number(OS_LCA$X95.CI, 2, decimals=T),
    Pvalue = pval,
    stringsAsFactors=FALSE
)

plotHRTable(mydf, useClass = T, useWeight = F, useRank = F, cex = 0.75, classpos = -0.7, xmin = -2.5)

```

#KM Curves

```{r}
library(survival)

data <- patient_data

data$SurvObj.os <- with(data, Surv(ostime, osevent))
data$SurvObj.pfs <- with(data, Surv(pfstime, pfsevent))

col=c("red", "red", "blue", "blue", "magenta", "magenta") 
lty=c(1,2,1,2,1,2)
```

##OS

```{r}

# rename
data$Class <- data$Class.OS

km <- survfit(SurvObj.os ~ Class + TRT, data=data)
plot(km, col=col, lty=lty, xlab="Overall Survival (days)", ylab="Probability of Survival")
legend("topright", col=col, legend = names(km$strata), lty=lty, bty="n", cex=0.8)
print(km)

survdiff(SurvObj.os ~ Class, data=data)

survdiff(SurvObj.os[Class==1] ~ TRT[Class==1], data=data)
survdiff(SurvObj.os[Class==2] ~ TRT[Class==2], data=data)
survdiff(SurvObj.os[Class==3] ~ TRT[Class==3], data=data)
```

```{r, fig.height=1.8, fig.width=10}
ggrisktable(km, data=data) + theme_cleantable()
```


#Compare Classes of FRET and FULL LCA

```{r}
as.numeric.factor <- function(x) {as.numeric(levels(x))[x]}
data <- patient_data[patient_data$FRET.cohort==1,]
data$Class.FRET.OS <- as.numeric.factor(data$Class.FRET.OS)
data$Class.OS <- as.numeric.factor(data$Class.OS)
```

```{r, echo=F}
plot(jitter(data$Class.FRET.OS) ~ jitter(data$Class.OS), pch=20, col=rgb(0.1, 0.2, 0.8, 0.3), 
     xaxp=c(1,3,2), yaxp=c(1,2,1), xlab="Full OS LCA Class", ylab="FRET OS LCA Class", 
     xlim=c(0.6,3.4), ylim=c(0.6, 2.4))
abline(h=1.5)
abline(v=1.5)
abline(v=2.5)

n <- table(data$Class.FRET.OS, data$Class.OS)
x <- c(1, 1, 2, 2, 3, 3)
y <- c(1.35, 2.35, 1.35, 2.35, 1.35, 2.35)
text(x, y, n)

```

Cohen's Kappa

```{r}
library(irr)

kappa2(data[,c("Class.FRET.OS", "Class.OS")])

```

Calculate the means and standard deviations from 100,000 random group assignments with the same number per subclass as the real data. Also do permutations test and see how many random group are as, or more, extreme as the real data.

```{r, ovelapPermutations, echo=F, eval=F}
# Calculate the confidence intervals for the random case
library(randomizr)

N = 10     # just for speed when testing
#N = 100000
count_extreme = 0

old1 <- sum(data$Class.FRET.OS==1, na.rm = T)
old2 <- sum(data$Class.FRET.OS==2, na.rm = T)
new1 <- sum(data$Class.OS==1, na.rm = T)
new2 <- sum(data$Class.OS==2, na.rm = T)
new3 <- sum(data$Class.OS==3, na.rm = T)

l <- vector('list', N)
for(i in 1:N){
  # Assign patients to 2 classes in same proportion as FRET OS LCA
  s1 <- complete_ra(N = 398, m_each = c(old1, old2))
  # Assign patients to 3 classes in same proportion as Full OS LCA
  s2 <- complete_ra(N = 398, m_each = c(new1, new2, new3))
  # Make the confusion matrix
  t <- table(s1, s2)
  l[[i]] <- t
  
  # We hope Class 1 to Class 1 overlap n will be bigger than the random version t
  # Count how many times the other is true
  if (t[1,1] >= n[1,1]) count_extreme = count_extreme + 1
}

arr <- array( unlist(l) , c(2,3,n) )
m <- apply( arr , 1:2 , mean )
s <- apply( arr , 1:2 , sd )
random_ms_text <- paste0(signif(m, 3), "±", signif(s, 3))
random_ms_text <- matrix(random_ms_text, ncol=3, byrow=FALSE)
print("Class number mean and sd.")
print(random_ms_text)

#low <- m - 1.96*s
#high <- m + 1.96*s
#random_ci_text <- paste0("[", signif(low, 3), ",", signif(high, 3), "]")

z <- (as.matrix(n) - m)/(s)
p_values <- 2 * pnorm(-abs(z))
print("p-values.")
print(p_values)

if(count_extreme > 0){
  print(paste("Permutations: ", count_extreme, "/ ", N, " => p-value =", count_extreme/N))
} else {
  print(paste("Permutations: 0 / ", N, " => pvalue <", 1/N))
}
```


#Session Information

```{r}
sessionInfo()
```
