---
title: "Compare LCA Classes"
author: "P Barber"
date: "30 November 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
load(file = "COIN_Final.Rdata")
as.numeric.factor <- function(x) {as.numeric(levels(x))[x]}
data <- patient_data[patient_data$FRET.cohort==1,]
data$Class.FRET.OS <- as.numeric.factor(data$Class.FRET.OS)
data$Class.OS <- as.numeric.factor(data$Class.OS)
```

```{r, echo=F}
plot(jitter(data$Class.FRET.OS) ~ jitter(data$Class.OS), pch=20, col=rgb(0.1, 0.2, 0.8, 0.3), 
     xaxp=c(1,3,2), yaxp=c(1,2,1), xlab="Full OS LCA Class", ylab="FRET OS LCA Class", 
     xlim=c(0.6,3.4), ylim=c(0.6, 2.4))
abline(h=1.5)
abline(v=1.5)
abline(v=2.5)

n <- table(data$Class.FRET.OS, data$Class.OS)
x <- c(1, 1, 2, 2, 3, 3)
y <- c(1.35, 2.35, 1.35, 2.35, 1.35, 2.35)
text(x, y, n)

```

Cohen's Kappa

```{r}
library(irr)

kappa2(data[,c("Class.FRET.OS", "Class.OS")])

```

Calculate the means and standard deviations from 100,000 random group assignments with the same number per subclass as the real data. Also do permutations test and see how many random group are as, or more, extreme as the real data.

```{r, echo=F}
# Calculate the confidence intervals for the random case
library(randomizr)

N = 100000
count_extreme = 0

old1 <- sum(data$Class.FRET.OS==1, na.rm = T)
old2 <- sum(data$Class.FRET.OS==2, na.rm = T)
new1 <- sum(data$Class.OS==1, na.rm = T)
new2 <- sum(data$Class.OS==2, na.rm = T)
new3 <- sum(data$Class.OS==3, na.rm = T)

l <- vector('list', N)
for(i in 1:N){
  # Assign patients to 2 classes in same proportion as FRET OS LCA
  s1 <- complete_ra(N = 398, m_each = c(old1, old2))
  # Assign patients to 3 classes in same proportion as Full OS LCA
  s2 <- complete_ra(N = 398, m_each = c(new1, new2, new3))
  # Make the confusion matrix
  t <- table(s1, s2)
  l[[i]] <- t
  
  # We hope Class 1 to Class 1 overlap n will be bigger than the random version t
  # Count how many times the other is true
  if (t[1,1] >= n[1,1]) count_extreme = count_extreme + 1
}

arr <- array( unlist(l) , c(2,3,n) )
m <- apply( arr , 1:2 , mean )
s <- apply( arr , 1:2 , sd )
random_ms_text <- paste0(signif(m, 3), "±", signif(s, 3))
random_ms_text <- matrix(random_ms_text, ncol=3, byrow=FALSE)
print("Class number mean and sd.")
print(random_ms_text)

#low <- m - 1.96*s
#high <- m + 1.96*s
#random_ci_text <- paste0("[", signif(low, 3), ",", signif(high, 3), "]")

z <- (as.matrix(n) - m)/(s)
p_values <- 2 * pnorm(-abs(z))
print("p-values.")
print(p_values)

if(count_extreme > 0){
  print(paste("Permutations: ", count_extreme, "/ ", N, " => p-value =", count_extreme/N))
} else {
  print(paste("Permutations: 0 / ", N, " => pvalue <", 1/N))
}
```

#Session Information

```{r}
sessionInfo()
```

